### ISSUE TITLE
building the lib

### ISSUE THREAD

**Issue by jbensabat** [LSDtopotools/LSDTopoTools2#13]
Hello 
I am building the lib under MSVC 
everything went smooth except in file LSDFloodPlain.cpp where there are two includes from the boost library

boost/numeric/mtl
boost/numeric/linear_algebra

These do not seem to be part of the boost distribution. I managed to find mtl but not linear_algebra
can you please indicate where linear_algebra can be found or alternatively if there is an implementation with the boost ublas 
best
jac

**Comment by simon-m-mudd** [comment]
Hello jac, I am slightly confused by this since these two libraries are only used in LSDRasterModel, which is not used in any of the binaries in LSDTopoTools2. 

You can find the header files for boost and mtl, in a minimal distribution, within the MuddPILE github repo:
 [https://github.com/LSDtopotools/MuddPILE](https://github.com/LSDtopotools/MuddPILE)

(you will unzip the file inside the boost_mtl_minimal directory).

**Comment by jbensabat** [comment]
Good morning and thanks a lot for your answer 
I am building the lib so it includes all the cpp files in the directory.
I should place another issue but is there an app that not only extracts channels but also their watershed ?
I am trying to compare the performance of this lib to the performance of the IOWA TauDEM

thanks 
jac

**Comment by simon-m-mudd** [comment]
Hello jac,

The way the code is organised is there are programs in the lsdtt-drivers that automate use of the objects to get desired results. If you want to create your own workflows directly using the library, you should be able to see the code examples there to do what you would like to do. 

For extracting watersheds there are various routines for getting outlets, creating channel networks, getting basins, and that sort of thing. But a minimalistic version of getting a basin is the following:

```
    // Assume you have loaded a DEM into topography_raster. First get the filled raster
    LSDRaster filled_topography,carved_topography;
    carved_topography = topography_raster.Breaching_Lindsay2016();
    filled_topography = carved_topography.fill(this_float_map["min_slope_for_fill"]);
    
    // get the flow info object. boundary_conditions is a string vector with 4 elements, all being "n"
    LSDFlowInfo FlowInfo(boundary_conditions,filled_topography); 

    // get all the upstream nodes of a point and print to a raster
    float x_loc = 0;   // enter a location in UTM coordinates
    float y_loc = 0;
    int outlet_location = FlowInfo.get_node_index_of_coordinate_point(x_loc,y_loc);
    vector<int> nodeindexvec = FlowInfo.get_upslope_nodes_include_outlet(outlet_location);
    LSDIndexRaster upstream_nodes = FlowInfo.write_NodeIndexVector_to_LSDIndexRaster(nodeindexvec);

    // Then write the index raster of the basin using the write_raster function
```

**Comment by jbensabat** [comment]
Good morning 
thanks a lot for your help.
Indeed I an trying to see if we can use LSDT as a library of tools.
but first we need to build it as it has a substantial amount of dependencies.
thanks
jac
