### ISSUE TITLE
Compilation error with MSVC 2022

### ISSUE THREAD

**Issue by jbensabat** [LSDtopotools/LSDTopoTools2#14]
Hello 
I am building the lib with MSVC 2022 using CMAKE
in file LSDRasterAggregator.cpp the function 

LSDRaster LSDRasterAggregator::create_flux_raster(vector<string> raster_types)
{
  cout << "Let me check the raster types for you. " << endl;
  bool can_proceed = check_raster_types(raster_types);

  string raster_ext = "bil";
  float multiplier;

  vector<LSDRaster> RasterVec;
  if(can_proceed)
  {
    cout << "The rasters exist, I will continue." << endl;
    int n_types = int(raster_types.size());
    string this_type;

    // This loads the rasters
    for (int i = 0; i< n_types; i++)
    {
      string full_raster_name = path+raster_filenames[raster_types[i]];
      LSDRaster this_raster(full_raster_name,raster_ext); 
      RasterVec.push_back(this_raster);  
    }

    // now loop through the rasters, multiplying them
    int NRows = RasterVec[0].get_NRows();
    int NCols = RasterVec[0].get_NCols();
    for(int row = 0; row<NRows; row++)
    {
      for(int col = 0; col<NCols; col++)
      {
        cout << "WORKING HERE LINE 334" << endl;

      }

    }
  }
  else
  {
    cout << "You can't perform this operation since I don't have the rasters." << endl;

  }

  }
generates a compilation error as it does not return anything 
What should it return ?
thanks 
jac

**Comment by simon-m-mudd** [comment]
Hello Jac, LSDRasterAggregator is a bit of code I started and then never implemented. No other functions call the create_flux_raster function. 

You can remove this object from the cmake_lists.
Alternativly you can add the following to the bottom of that function:

LSDRaster EMPTY;
return EMPTY;
