### ISSUE TITLE
Drainage density analysis

### ISSUE THREAD

**Issue by BenjaminGuerreroLewin** [LSDtopotools/LSDTopoTools2#15]
I have been following the instructions to perform the DD analysis, and I encountered a problem (a fatal error, indeed) when running the channel junctions code (i.e., drainage_density_step1_junctions.out).

To give you a not-so-little bit of background:
1. I am working in /LSDTopoTools/Topographic_projects/Guadalupe_NM
2. I extracted the channel network using the Wiener method (is the Dreich method not working in my computer only?).
3. I downloaded the drainage density driver for Guadalupe (the download was a html code, which I replaced for what appears in Github/tutorial).
4. I downloaded the LSDTopoTools_DrainageDensity folder and placed it in my working folder (i.e., /LSDTopoTools/Topographic_projects/Guadalupe_NM).
5. 'I performed' the first step of the DD analysis: in the driver_functions_DrainageDensity folder, 'make -f drainage_density_step1_junctions.make', which created the '.out' file.
6. In the driver_functions_DrainageDensity folder, I run the '.out' program with: ./drainage_density_step1_junctions.out /LSDTopoTools/Topographic_projects/Guadalupe_NM/ drainage_density_guadalupe.driver
7. Fatal Error:
/drainage_density_step1_junctions.out /LSDTopoTools/Topographic_projects/Guadalupe_NM/ drainage_density_guadalupe.driver
The path is: /LSDTopoTools/Topographic_projects/Guadalupe_NM/ and the filename is: drainage_density_guadalupe.driver
FATAL ERROR: the header file "/LSDTopoTools/Topographic_projects/Guadalupe_NM/drainage_density_guadalupe.driver" doesn't exist

Below are the drivers that I have used (although I have tried variations of these in a useless effort to solve the problem)

channel extraction driver:
_read path: ./
write path: ./
read fname: Guadalupe_DEM
write fname: Guadalupe_DEM
channel heads fname: NULL
min_slope_for_fill: 0.0001
threshold_contributing_pixels: 1000
connected_components_threshold: 100
print_area_threshold_channels: false
print_wiener_channels: true
print_pelletier_channels: false
print_dreich_channels: false
write_hillshade: true
print_stream_order_raster: true
print_sources_to_raster: true
print_sources_to_csv:true_

drainage density.driver:
_Guadalupe_DEM
Guadalupe_DEM_W_CN # also tried Guadalupe_DEM
0.0001
2
6_

Any idea why this could be happening?

Best,
Benjamin

**Comment by BenjaminGuerreroLewin** [comment]
Changing the second drainage density driver filename to Guadalupe_DEM_Wsources fixed the problem :)

**Comment by simon-m-mudd** [comment]
I'm glad that worked!
When I get a chance I will re-do this analysis in a python notebook to make sure it is all up to date.
