### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by hsgarciad** [LSDtopotools/LSDTopoTools2#16]
Hello,

I've trying to run some basic analysis for hillslopes and I just keep getting the following error:

```
_I've now ingested the channel source nodes. Yum yum. Sources are tasty.
The number of sources is: 567
I am now getting the junction network...
Got the junction network
printing channels to csv...
I am getting the channel nodes and junctions.
Finished getting the nodes and junctions.
Segmentation fault (core dumped)_

```
I've installed LSDTopoTools on Ubuntu following the tutorial (cloning from GitHub) and the error just keep coming. Later I tried installing an older version but nothing. I'm working on a machine with 62 GB of RAM, so I'm not sure if this is a memory issue. If anyone else has experienced the same problem, I'd appreciate it if you share your experience with me on how you solved it.

Thanks!

**Comment by simon-m-mudd** [comment]
Did you resolve this yourself and if so what was the fix?

**Comment by hsgarciad** [comment]
Yes I did. After running through several steps, I was able to make LSDTopoTools functional on my PC. Here is what I did. First, I installed the software by cloning the package from Github. Once I followed the installation steps specified in the webpage, I did this:

#Install build-essential
sudo apt-get install -y build-essential

#install pk-config
sudo apt-get install pkg-config

#Install OpenCV
 sudo apt-get install libopencv-dev

#Export OpenCV path
OpenCV_DIR=/usr/share/OpenCV

#Add the following line to the CMakeLists.txt file located at src. The line should go below the #comment #OpenCV
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${OpenCV_DIR}/cmake-modules)

#Install libfftw3
sudo apt-get install -y libfftw3-dev

#Compile the code after cd to the src folder if you're in a different folder
./build.sh (or bash build.sh)

Some of these packages had to be installed before, but for some reason, my unit didn't do that on time. Also, I had to be careful with the coordinate system of the DEMs (something specified in another post). I strongly recommend to use gdal instead of trying with other GIS environments to transform your DEMs.

Best,
Helbert
