### ISSUE TITLE
Default installation directory

### ISSUE THREAD

**Issue by awickert** [LSDtopotools/LSDTopoTools2#4]
`lsdtt2_setup.sh` uses a default installation directory. I think that we could do one or both of the following:
* Let the user know to clone it into that directory so they don't confusingly end up with two copies of LSDTT -- or if they do, it is intentional.
* Have an option (or another script) for a "local install", which will install LSDTT2 within whatever path contains `lsdtt2_setup.sh`.

**Comment by simon-m-mudd** [comment]
I am thinking about deleting this script completely: Eric Hutton has created a conda package so installing now is as simple as
`$ conda install -c conda-forge lsdtopotools`

**Comment by awickert** [comment]
Anaconda tends to overrun system Python packages on Linux and cause errors across a swath of programs. Or at least it has in the past. So I think that there could be value in retaining a local install script of some kind, but maybe an updated `README.md`?

**Comment by simon-m-mudd** [comment]
I've updated the setup script so it includes a number of user prompts. You can look for a pre-existing installation, install somewhere of your choice, install in your home directory, or use conda (if you've got it).
