### ISSUE TITLE
Export receiver_node

### ISSUE THREAD

**Issue by awickert** [LSDtopotools/LSDTopoTools2#5]
I just started to build a tool to convert LSDTT outputs into a network of channel segments bounded by [tributary junctions / channel heads / river mouths]: https://github.com/umn-earth-surface/LSDTT-network-tool.

To convert the LSDTT outputs into this networked structure, I need `receiver_node` to print to a file. Is there some existing option that I have missed (or a new one that we could add) to do this? I do have one working file with this info thanks to @fclubb, so this isn't holding up my development.

Motivation: this will help with visualization and for me to integrate LSDTT into my own modeling efforts and Landlab `NetworkModelGrid` development.

**Comment by bgailleton** [comment]
Hi Andy,
This is indirectly possible in"the python version of lsdtopytools, where I added the possibility to get the receiver informations in the exported river network. However this require the python tools to be installed, and the option is a bit hacky. The other thing is that it gives the node index, but then extra steps would be required to convert it into the index of the river network file.
I could add an option tomorrow that add a colum to the CSV output with the index of the receiver within the CSV file? Is that what you have in mind? Which driver are you using?

**Comment by awickert** [comment]
Thanks @bgailleton! I tried https://pypi.org/project/lsdtopytools/ earlier but it ran into install issues that I never diagnosed. Very happy to talk about Python bindings in general, though!

I'm using the `lsdtt-chi-mapping` driver with `print_channels_to_csv: true`.

Upon looking at the code, it seems that this is associated with `JunctionNetwork.PrintChannelNetworkToCSV(FlowInfo, channel_csv_name);`. I checked this to see about changing it myself. But then I saw all of these other options, including `print_junctions_to_csv`. I am going to try this as well and will get back to you. The junctions are the main thing that I need, though having all stream indices is handy.

So short answer: **yes** to exporting stream node indices, but might have a more informed reply later on.

**Comment by awickert** [comment]
I just set `print_junctions_to_csv: True`. It's additional great info! But I think that I still need the IDs of all of the nodes / segments feeding into this junction. Therefore, the  `receiver_node` numbers would still be quite helpful!

If you could guide me to the right file(s) to edit, I'd be happy to do so. Or if you'd like to do it yourself, I'd be even happier -- but you shouldn't feel any obligation! I will however share all my code for creating river networks as sets of nodes and links.

**Comment by simon-m-mudd** [comment]
I have added the receiver junction index as a column to the csv files . You can keep the same flag in the driver file `print_junctions_to_csv: true` in the various programs.
