### ISSUE TITLE
minor change to build system

### ISSUE THREAD

**Issue by mhagdorn** [LSDtopotools/LSDTopoTools2#6]
In order to get out-of-source builds to work you need to apply the attached [fix_build.patch.gz](https://github.com/LSDtopotools/LSDTopoTools2/files/5057388/fix_build.patch.gz)

You can then do
```
mkdir build
cd build
cmake ../src/ -DCMAKE_INSTALL_PREFIX=PREFIX 
make
make install
```

**Comment by simon-m-mudd** [comment]
Applied the patch
