### ISSUE TITLE
Inconsistency in install instructions and current install causing errors?

### ISSUE THREAD

**Issue by jmdelvecchio** [LSDtopotools/LSDTopoTools2#9]
Hi! I am following the instructions to install in the [Windows Subsystem for Linux](https://lsdtopotools.github.io/LSDTT_documentation/LSDTT_installation.html#_installing_lsdtopotools_using_windows_subsystem_for_linux) which until this point had been going smoothly. When I go to run lsdtt2_setup.sh I get a message to find the directory (whether I say yes or no it always sends me to the same directory) and then I get this message:

_Your current directory is:
/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2
Where yould you like me to put LSDTopoTools?
I will make an LSDTopoTools directory here if it doesn't exist
1 -- I am in an LSDTopoTools docker container. Make all the choices for me.
2 -- Put it in this directory.
3 -- Put it in my home directory.
4 -- Put it somewhere else. I'll ask you where you want it if you make this choice.
5 -- I have conda. Just install it. Note that this doesn't create any of the test data directories_

This isn't addressed in the instructions, so I choose 2 which seems the best answer. But I get the following messages:

_You have chosen to install LSDTopoTools here:
/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2
LSDTopoTools directory doesnt' exist. I'm making one
Cloning the LSDTopoTools2 repository
Cloning into '/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2/LSDTopoTools/LSDTopoTools2'..._

So I get this weird nesting of the directories. If I try it again, I get this:

_You have chosen to install LSDTopoTools here:
/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2
LSDTopoTools directory exists!
The LSDTopoTools2 repository exists, updating to the latest version.
fatal: not a git repository: '/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2/LSDTopoTools/LSDTopoTools2.git'
The current directory is:
/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2/LSDTopoTools/LSDTopoTools2/src
Calling the build script.
The full directory for binary files is:
/home/jmdelvecchio/LSDTopoTools/LSDTopoTools2/LSDTopoTools/LSDTopoTools2/bin_

And both give me, at the end, 

_build.sh: 11: cmake: not found
build.sh: 13: make: not found
build.sh: 14: make: not found_

"fatal" doesn't sound great nor do those builds not found. Then, it seems like to code automatically tries to add LSDTT to my path (whereas it's a user step in the instructions), but it comes up with this wild path /home/jmdelvecchio/LSDTopoTools/LSDTopoTools2/LSDTopoTools/LSDTopoTools2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games etc. etc. that is just a mess. Predictably, the steps in [2.1.2. for basic analyses](https://lsdtopotools.github.io/LSDTT_documentation/LSDTT_basic_usage.html) don't work. Any advice? Let me know if you need more info. Thanks!

PS guide has so far been very thorough and has been pretty smooth besides this!

**Comment by simon-m-mudd** [comment]
Hi Joanmarie,
This is going to be short for now: I will try to do a full fix to the docs when I have some time.
On WSL: If you choose option 2 you should have a "clean" directory. So just delete all the created directories. It will make a new LSDTopoTools directory for you. 
The build errors are coming because cmake and make are not installed. You need to add these. 
$ sudo apt-get install make
$ sudo apt-get install cmake

but maybe that will miss some other things I haven't thought of so you could alternativly do:
$ sudo apt-get update
$ sudo apt-get install build-essential

then run the setup script.

*Alternatively* 
Download miniconda into the linux system
then
$ conda install -c conda-forge lsdtopotools

This latter way is **much** easier since it installs lsdtopotools on your command line

**Comment by jmdelvecchio** [comment]
Perfect, worked like a charm! I used
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc
rm Miniconda3-latest-Linux-x86_64.sh

from [this post ](https://gist.github.com/kauffmanes/5e74916617f9993bc3479f401dfec7da)to do it and was able to run the basic analysis. Conda to the rescue, thanks so much!
